const PORT = process.env.PORT || 7000;

const HEALTH_CHECK_TIMEOUT_MS = 2500;
const HEALTH_CHECK_INTERVAL_MS = 3000;
const FAILURE_THRESHOLD = 3;
const VIRTUAL_NODES_PER_WEIGHT = 20;
const RAFT_WRITE_TIMEOUT_MS = 6000;

const LEADER_DISCOVERY_MAX_ATTEMPTS = 4;
const RETRY_INITIAL_DELAY_MS = 200;
const RETRY_MAX_DELAY_MS = 1600;

module.exports = {
  PORT,
  HEALTH_CHECK_TIMEOUT_MS,
  HEALTH_CHECK_INTERVAL_MS,
  FAILURE_THRESHOLD,
  VIRTUAL_NODES_PER_WEIGHT,
  RAFT_WRITE_TIMEOUT_MS,
  LEADER_DISCOVERY_MAX_ATTEMPTS,
  RETRY_INITIAL_DELAY_MS,
  RETRY_MAX_DELAY_MS,
};
