const PORT = process.env.PORT || 7000;

const HEALTH_CHECK_TIMEOUT_MS = 2500;
const HEALTH_CHECK_INTERVAL_MS = 3000;
const FAILURE_THRESHOLD = 3;
const VIRTUAL_NODES_PER_WEIGHT = 20;

module.exports = {
  PORT,
  HEALTH_CHECK_TIMEOUT_MS,
  HEALTH_CHECK_INTERVAL_MS,
  FAILURE_THRESHOLD,
  VIRTUAL_NODES_PER_WEIGHT,
};
