events {}

http {
    upstream load_balancer_service {
        server load-balancer:7000;
    }

    upstream dashboard_service {
        server dashboard:3000;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://dashboard_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://load_balancer_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /lb/ {
            proxy_pass http://load_balancer_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /cluster/ {
            proxy_pass http://load_balancer_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /gateway/health {
            return 200 "Nginx Gateway is running\n";
        }
    }
}